### ISSUE TITLE
Error at ED step with updated mashr packages.

### ISSUE THREAD

**Issue by hsun3163** [gaow/neuro-twas#42]
At the extreme deconvolution steps of the mixture_prior pipeline, following error occurs. The reason for the issue is yet to be updated.

![Screen Shot 2021-05-04 at 10 14 03 AM](https://user-images.githubusercontent.com/54919134/117017349-87168e00-acc1-11eb-91eb-2f8ec1edb629.png)

**Comment by gaow** [comment]
@hsun3163 do you know why we have NA's in the first place? I'm not sure if this is the right "fix" to the issue. I'm asking my colleague to take a look at this see if she has an input.
